//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.jspapps.test.pokemon_service.domain.pokemon;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jspapps.test.pokemon_service.domain.pokemon package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jspapps.test.pokemon_service.domain.pokemon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PokemonListCommandRequest }
     * 
     * @return
     *     the new instance of {@link PokemonListCommandRequest }
     */
    public PokemonListCommandRequest createPokemonListCommandRequest() {
        return new PokemonListCommandRequest();
    }

    /**
     * Create an instance of {@link PokemonListQueryResponse }
     * 
     * @return
     *     the new instance of {@link PokemonListQueryResponse }
     */
    public PokemonListQueryResponse createPokemonListQueryResponse() {
        return new PokemonListQueryResponse();
    }

    /**
     * Create an instance of {@link PokemonDetail }
     * 
     * @return
     *     the new instance of {@link PokemonDetail }
     */
    public PokemonDetail createPokemonDetail() {
        return new PokemonDetail();
    }

}
